server.port=8080
spring.application.name=api-gateway
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true
# Route AUTH SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**
# Route TABLE and MENU SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=table-menu-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/**
# JWT
imthang.jwt.base64-secret=LVIe88d1bftZTX8Ykz7TTUd6cR5Q6qL0o0ivPrbot2GBX2YBw9pT2CgGus2aXhHmRYl4NfdMDI7G/hYxBxw33A==
imthang.jwt.access-token-validity-in-seconds=90000
imthang.jwt.refresh-token-validity-in-seconds=90000
